### ISSUE TITLE
[Question] Why using a custom `fetch` implementation over a library like `axios`?

### ISSUE THREAD

**Issue by olivierobert** [pongdanaiNil/code-challenge-frontend#3]
https://github.com/pongdanaiNil/code-challenge-frontend/blob/development/src/features/customFetchBase.ts implements the logic to make API requests. The implementation is non-trivial (it uses `Mutex`, for instance). So it could become a source of bugs if there is any implementation errors. So why rely on a custom implementation instead of a battle-tested solution like https://www.npmjs.com/package/axios?

**Comment by pongdanaiNil** [comment]
I used Redux Toolkit for state management, and there is an RTK Query addon included in the Redux Toolkit package.

RTK Query is a data fetching and caching tool that helps simplify common data fetching scenarios. In this case, it provides states when performing data fetching that make doing the skeleton loader easier. However, it must perform some custom implementation in some cases, such as refreshing the token while the user is still using the web app even after the access token has expired.

[In this file](https://github.com/pongdanaiNil/code-challenge-frontend/blob/development/src/features/customFetchBase.ts), I will use fetchBaseQuery ([in this document](https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery)) as a data fetching function, and, in the event that the response gets a 401 error code, that means the access token in the header has expired. I set Mutex to lock state so that every request after this will not send until Mutex releases. then try to send a request to refresh the token, set a new access token and a new refresh token, and then release Mutex.

Unlike Axios, the above implementation can be done easily by configuring interceptors. This is a tradeoff that has to be done manually with caution. but in exchange, there were many utility functions that made development easier, especially for client-side render apps. RTK Query also provides caching and automatic retries that can improve the performance of an application.

**Comment by olivierobert** [comment]
Thank you for all the details 🤩 The link to https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery was a good addition as it can provide more context.

As for the simplicity of usage, Axios also support interceptors: https://axios-http.com/docs/interceptors. So both solutions might be more on equal footing on that front. This issue is not a blocker for this project so it can be closed for now.
